version: '3.8'

services:
  drupal:
    build:
      context: ./locale-drupal
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./locale-drupal/web/modules:/var/www/html/modules
      - ./locale-drupal/web/profiles:/var/www/html/profiles
      - ./locale-drupal/web/themes:/var/www/html/themes
      - ./locale-drupal/web/sites:/var/www/html/sites
    restart: always
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

  react:
    container_name: react
    build:
      context: ./locale-react
      dockerfile: Dockerfile
    volumes:
      - './locale-react:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
