# Generated by Django 3.2.25 on 2024-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_auto_20241009_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_phone_number', models.CharField(max_length=20)),
                ('store_physical_location', models.TextField()),
                ('store_mailing_location', models.TextField()),
                ('store_billing_address', models.TextField()),
                ('store_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
